name: Check for updated firmware versions for stuff I own
on:
  push:
    paths:
      - 'bin/fwversions**'
  schedule:
    - cron: "15 1 * * 0"
  workflow_dispatch:
jobs:
  fwversions:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: cachix/install-nix-action@v17
        with:
          install_url: https://github.com/numtide/nix-flakes-installer/releases/download/nix-2.4pre20210823_af94b54/install
          extra_nix_config: |
            experimental-features = nix-command flakes
      - run: ./bin/fwversions
